### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by travislynn** [roguebeats/roguebeats.github.io#1]
I attempted ng deploy this morning.  Not sure if it was working before, but it was definitely not working after.

Access to script at 'https://github.com/roguebeats/runtime-es2015.34eb13adbe14d232f907.js' from origin 'https://roguebeats.github.io' has been blocked by **CORS** policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by m-england** [comment]
I had the wrong base href for the site.  I believe this is fixed again.
